apiVersion: apps/v1
kind: Deployment
metadata:
  name: goweb-deployment
  labels:
    app: goweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goweb
  template:
    metadata:
      labels:
        app: goweb
    spec:
      containers:
        - name: goweb
          image: goweb:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
